version: '3'
services:
  sdkgen:
    build: .
    environment:
      SDKGEN_TYPE: "${SDKGEN_TYPE}"
      SDKGEN_CLIENT_ID: "${SDKGEN_CLIENT_ID}"
      SDKGEN_CLIENT_SECRET: "${SDKGEN_CLIENT_SECRET}"
      SDKGEN_BASE_URL: "${SDKGEN_BASE_URL}"
      SDKGEN_NAMESPACE: "${SDKGEN_NAMESPACE}"
    volumes:
      - ./output:/usr/src/sdkgen/output
