version: '3'
services:
  sdkgen:
    build: .
    environment:
      TYPE: "client-java"
      CLIENT_ID: ""
      CLIENT_SECRET: ""
      BASE_URL: ""
      NAMESPACE: "app.sdkgen.generator"
    volumes:
      - ./output:/usr/src/sdkgen/output
