// artifact automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type Artifact struct {
	Id           string    `json:"id"`
	Name         string    `json:"name"`
	File         string    `json:"file"`
	GenerateDate time.Time `json:"generateDate"`
}
