// ArtifactTag automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import (
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type ArtifactTag struct {
	internal *sdkgen.TagAbstract
}

// Get Returns a artifact
func (client *ArtifactTag) Get(projectId string, versionId string, artifactId string) (Artifact, error) {
	pathParams := make(map[string]interface{})
	pathParams["project_id"] = projectId
	pathParams["version_id"] = versionId
	pathParams["artifact_id"] = artifactId

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/project/:project_id/version/:version_id/artifact/:artifact_id", pathParams))
	if err != nil {
		return Artifact{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return Artifact{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return Artifact{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Artifact{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response Artifact
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Artifact{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Artifact{}, errors.New("could not unmarshal JSON response")
		}

		return Artifact{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Artifact{}, errors.New("could not unmarshal JSON response")
		}

		return Artifact{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Artifact{}, errors.New("could not unmarshal JSON response")
		}

		return Artifact{}, &MessageException{
			Payload: response,
		}
	default:
		return Artifact{}, errors.New("the server returned an unknown status code")
	}
}

// GetAll Returns all artifacts for a version
func (client *ArtifactTag) GetAll(projectId string, versionId string, startIndex int, count int, search string) (ArtifactCollection, error) {
	pathParams := make(map[string]interface{})
	pathParams["project_id"] = projectId
	pathParams["version_id"] = versionId

	queryParams := make(map[string]interface{})
	queryParams["startIndex"] = startIndex
	queryParams["count"] = count
	queryParams["search"] = search

	u, err := url.Parse(client.internal.Parser.Url("/project/:project_id/version/:version_id/artifact", pathParams))
	if err != nil {
		return ArtifactCollection{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return ArtifactCollection{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return ArtifactCollection{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return ArtifactCollection{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response ArtifactCollection
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return ArtifactCollection{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return ArtifactCollection{}, errors.New("could not unmarshal JSON response")
		}

		return ArtifactCollection{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return ArtifactCollection{}, errors.New("could not unmarshal JSON response")
		}

		return ArtifactCollection{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return ArtifactCollection{}, errors.New("could not unmarshal JSON response")
		}

		return ArtifactCollection{}, &MessageException{
			Payload: response,
		}
	default:
		return ArtifactCollection{}, errors.New("the server returned an unknown status code")
	}
}

func NewArtifactTag(httpClient *http.Client, parser *sdkgen.Parser) *ArtifactTag {
	return &ArtifactTag{
		internal: &sdkgen.TagAbstract{
			HttpClient: httpClient,
			Parser:     parser,
		},
	}
}
