// Client automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import (
	"github.com/apioo/sdkgen-go"
)

type Client struct {
	internal *sdkgen.ClientAbstract
}

func (client *Client) Generator() *GeneratorTag {
	return NewGeneratorTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Artifact() *ArtifactTag {
	return NewArtifactTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Version() *VersionTag {
	return NewVersionTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Project() *ProjectTag {
	return NewProjectTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Authorization() *AuthorizationTag {
	return NewAuthorizationTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Meta() *MetaTag {
	return NewMetaTag(client.internal.HttpClient, client.internal.Parser)
}

func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
	if err != nil {
		return &Client{}, err
	}

	return &Client{
		internal: client,
	}, nil
}
