// GeneratorTag automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type GeneratorTag struct {
	internal *sdkgen.TagAbstract
}

// Generate Generates a new SDK from the provided input
func (client *GeneratorTag) Generate(_type string, payload Passthru, namespace string, baseUrl string) (GeneratorResponse, error) {
	pathParams := make(map[string]interface{})
	pathParams["type"] = _type

	queryParams := make(map[string]interface{})
	queryParams["namespace"] = namespace
	queryParams["baseUrl"] = baseUrl

	u, err := url.Parse(client.internal.Parser.Url("/generator/generate/:type", pathParams))
	if err != nil {
		return GeneratorResponse{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	raw, err := json.Marshal(payload)
	if err != nil {
		return GeneratorResponse{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("POST", u.String(), reqBody)
	if err != nil {
		return GeneratorResponse{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return GeneratorResponse{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return GeneratorResponse{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response GeneratorResponse
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorResponse{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorResponse{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorResponse{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorResponse{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorResponse{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorResponse{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorResponse{}, &MessageException{
			Payload: response,
		}
	default:
		return GeneratorResponse{}, errors.New("the server returned an unknown status code")
	}
}

// GetTypes Shows all available generator types
func (client *GeneratorTag) GetTypes() (GeneratorTypes, error) {
	pathParams := make(map[string]interface{})

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/generator/types", pathParams))
	if err != nil {
		return GeneratorTypes{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return GeneratorTypes{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return GeneratorTypes{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return GeneratorTypes{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response GeneratorTypes
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorTypes{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorTypes{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorTypes{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorTypes{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorTypes{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorTypes{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorTypes{}, &MessageException{
			Payload: response,
		}
	default:
		return GeneratorTypes{}, errors.New("the server returned an unknown status code")
	}
}

func NewGeneratorTag(httpClient *http.Client, parser *sdkgen.Parser) *GeneratorTag {
	return &GeneratorTag{
		internal: &sdkgen.TagAbstract{
			HttpClient: httpClient,
			Parser:     parser,
		},
	}
}
