// generator_response automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type GeneratorResponse struct {
	Chunks map[string]string `json:"chunks"`
	Output string            `json:"output"`
}
