// generator_types automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type GeneratorTypes struct {
	Types []GeneratorType `json:"types"`
	Usage GeneratorUsage  `json:"usage"`
}
