// generator_type automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type GeneratorType struct {
	Name          string `json:"name"`
	FileExtension string `json:"fileExtension"`
	Mime          string `json:"mime"`
}
