// history automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type History struct {
	Id            string    `json:"id"`
	Specification string    `json:"specification"`
	GenerateDate  time.Time `json:"generateDate"`
}
