// HistoryTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import (
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go/v2"
	"io"
	"net/http"
	"net/url"
)

type HistoryTag struct {
	internal *sdkgen.TagAbstract
}

// Get Shows a specific past generator request
func (client *HistoryTag) Get(historyId string) (History, error) {
	pathParams := make(map[string]interface{})
	pathParams["history_id"] = historyId

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/history/:history_id", pathParams))
	if err != nil {
		return History{}, err
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return History{}, err
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return History{}, err
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return History{}, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response History
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return History{}, err
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return History{}, err
		}

		return History{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return History{}, err
		}

		return History{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return History{}, err
		}

		return History{}, &MessageException{
			Payload: response,
		}
	default:
		return History{}, errors.New("the server returned an unknown status code")
	}
}

// GetAll Shows all past executed generator requests
func (client *HistoryTag) GetAll(startIndex int, count int) (HistoryCollection, error) {
	pathParams := make(map[string]interface{})

	queryParams := make(map[string]interface{})
	queryParams["startIndex"] = startIndex
	queryParams["count"] = count

	u, err := url.Parse(client.internal.Parser.Url("/history", pathParams))
	if err != nil {
		return HistoryCollection{}, err
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return HistoryCollection{}, err
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return HistoryCollection{}, err
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return HistoryCollection{}, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response HistoryCollection
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return HistoryCollection{}, err
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 400:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return HistoryCollection{}, err
		}

		return HistoryCollection{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return HistoryCollection{}, err
		}

		return HistoryCollection{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return HistoryCollection{}, err
		}

		return HistoryCollection{}, &MessageException{
			Payload: response,
		}
	default:
		return HistoryCollection{}, errors.New("the server returned an unknown status code")
	}
}

func NewHistoryTag(httpClient *http.Client, parser *sdkgen.Parser) *HistoryTag {
	return &HistoryTag{
		internal: &sdkgen.TagAbstract{
			HttpClient: httpClient,
			Parser:     parser,
		},
	}
}
