// version automatically sdk by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type Version struct {
	Id         string     `json:"id"`
	Name       string     `json:"name"`
	Spec       string     `json:"spec"`
	File       string     `json:"file"`
	Changelog  string     `json:"changelog"`
	Artifacts  []Artifact `json:"artifacts"`
	InsertDate time.Time  `json:"insertDate"`
}
